Export FireBat table to CSV
bcgov/wps pull request #1271
Opened 2021-08-30 21:22 UTC by andrea-williams

2021-08-31 17:04 UTC, tessmgood approved these changes
Rad TY

2021-08-31 21:26 UTC, conbrad approved these changes

2021-08-31 21:52 UTC, Sybrand approved these changes
Approved with comments.

2021-08-31 21:52 UTC, Sybrand commented on web/cypress/support/fba-commands.ts
> +      // .get('button[title="Open"]')
Is this commented out code going to be used?

2021-08-31 21:54 UTC, Sybrand requested changes
Uh oh - found a bug.

If you selected a date for which there is no data, export selection fails without any kind of feedback for the user.

2021-08-31 22:12 UTC, andrea-williams commented
Exporting to CSV when a station is missing data now looks like this:
[FireBAT_2021-08-31 (2).csv](https://github.com/bcgov/wps/files/7087050/FireBAT_2021-08-31.2.csv)

2021-09-01 20:18 UTC, andrea-williams commented
> Totally not a big deal, but did notice, that on a station without a prediction - crown fraction burned is 0%. It should probably just be empty - instead of 0.
> 
> Looks good though.

Yeah I noticed that in the CSV too, but I figured that the fix was out of scope for this ticket since the table itself outputs 0 for CFB when it should just be empty.

2021-09-01 21:20 UTC, merged