Fire centre drop down
bcgov/wps pull request #1483
Opened 2021-10-27 20:08 UTC by conbrad

- Adds `api/fba/fire-centers` route
- Adds `fire_center_mapper` to marshall station results from WFWX1 into unque `FireCenter`s with their associated stations to serve to the frontend
- Selected a fire center on the frontend renders the list of associated stations

Naming note: Distinguishing this new page with the name `fba` as opposed to the existing `fba-calc`. Not sure if there is a better name yet.

# Test Links:
[Percentile Calculator](https://wps-pr-1483.apps.silver.devops.gov.bc.ca/)
[MoreCast](https://wps-pr-1483.apps.silver.devops.gov.bc.ca/morecast)
[C-Haines](https://wps-pr-1483.apps.silver.devops.gov.bc.ca/c-haines)
[FireBat](https://wps-pr-1483.apps.silver.devops.gov.bc.ca/fire-behaviour-calculator)
[FireBat bookmark](https://wps-pr-1483.apps.silver.devops.gov.bc.ca/fire-behaviour-calculator?s=266&f=c5&c=NaN&w=20,s=286&f=c7&c=NaN&w=16,s=1055&f=c7&c=NaN&w=NaN,s=305&f=c7&c=NaN&w=NaN,s=344&f=c5&c=NaN&w=NaN,s=346&f=c7&c=NaN&w=NaN,s=328&f=c7&c=NaN&w=NaN,s=1399&f=c7&c=NaN&w=NaN,s=334&f=c7&c=NaN&w=NaN,s=1082&f=c3&c=NaN&w=NaN,s=388&f=c7&c=NaN&w=NaN,s=309&f=c7&c=NaN&w=16,s=306&f=c7&c=NaN&w=NaN,s=1029&f=c7&c=NaN&w=NaN,s=298&f=c7&c=NaN&w=NaN,s=1108&f=c5&c=NaN&w=NaN,s=836&f=c7&c=NaN&w=NaN#state=2ec784ca-c46a-49d0-b2b3-1cf32a9015a2&session_state=7d9447c8-db66-4661-b4cb-03d2ac0d1d8f&code=32292df4-2bdf-4f90-a4a8-c8dbcda682a9.7d9447c8-db66-4661-b4cb-03d2ac0d1d8f.2b63f390-f3dc-43ae-89f2-016453863476)
[Fire Behaviour Advisory](https://wps-pr-1483.apps.silver.devops.gov.bc.ca/fire-behaviour-advisory)
[HFI Calculator](https://wps-pr-1483.apps.silver.devops.gov.bc.ca/hfi-calculator)

2021-11-02 22:18 UTC, tessmgood approved these changes
there is indeed a dropdown! exciting 
fba is a good name for now - it exactly matches the name of the document that this tool is ultimately producing. we'll see how users & stakeholders interpret it :)

2021-11-03 16:28 UTC, Sybrand requested changes

2021-11-03 16:28 UTC, Sybrand commented on api/app/routers/fba.py
> +    """ Returns daily metrics for each station code. """
This comment isn't relevant

2021-11-03 16:28 UTC, Sybrand commented on api/app/routers/fba.py
> +        response.headers["Cache-Control"] = "max-age=0"  # don't let the browser cache this
Why don't we cache this? It shouldn't change often.

2021-11-03 16:28 UTC, Sybrand commented on api/app/tests/test_fba_endpoint.py
> +fire_centers = AsyncIter([
Is this being used?

2021-11-03 16:28 UTC, Sybrand commented on api/app/wildfire_one/wfwx_api.py
> +    """ Get the fire centers. Replace hard coded centers once WFWX API supports them """
Doesn't look hard coded to me?

2021-11-03 17:27 UTC, andrea-williams approved these changes

2021-11-03 17:27 UTC, andrea-williams commented on web/src/features/fbaCalculator/components/FormalFBATable.tsx
> +const FormalFBATable = (props: FormalFBATableProps) => {
I'm not a big fan of the name of this component, but until we figure out specific names for the 2 FBA-related apps, I'll go with this

2021-11-03 17:56 UTC, conbrad commented on api/app/wildfire_one/schema_parsers.py
> +    return fire_centers
Let's discuss and do a find/replace follow up PR.

2021-11-03 17:57 UTC, conbrad commented on api/app/routers/fba.py
> +        response.headers["Cache-Control"] = "max-age=0"  # don't let the browser cache this
Copy/paste, already changed since Sy caught it earlier.

2021-11-03 18:09 UTC, JulianForeman approved these changes

2021-11-03 18:10 UTC, merged