Implement Metabase
bcgov/wps pull request #1625
Opened 2021-12-20 18:24 UTC by andrea-williams

2022-01-12 18:20 UTC, conbrad requested changes

2022-01-12 18:20 UTC, conbrad commented on openshift/metabase/oc_build_metabase.sh
> +export BASE_URL="https://raw.githubusercontent.com/bcgov/nr-showcase-devops-tools/master/tools/metabase/openshift"
Let's copy / augment this yaml file we're pulling here, it can change on us / get deleted otherwise.

2022-01-12 18:20 UTC, conbrad commented on openshift/metabase/oc_deploy_metabase.sh
> +export BASE_URL="https://raw.githubusercontent.com/bcgov/nr-showcase-devops-tools/master/tools/metabase/openshift"
Similar to the above

2022-01-12 18:20 UTC, conbrad commented on openshift/metabase/oc_network_policy_metabase.sh
> +export BASE_URL="https://raw.githubusercontent.com/bcgov/nr-showcase-devops-tools/master/tools/metabase/openshift"
Similar to the above.

2022-01-12 18:20 UTC, conbrad commented on openshift/metabase/oc_network_policy_metabase.sh
> +export NAMESPACE=e1e498-prod
I think these hardcoded namespaces should be parameterized so we can add metabase to our different environments.

2022-01-12 18:20 UTC, conbrad commented on openshift/metabase/oc_deploy_metabase.sh
> +export NAMESPACE=e1e498-dev
I think these hardcoded namespaces should be parameterized so we can add metabase to our different environments.

2022-01-12 18:20 UTC, conbrad commented on openshift/metabase/oc_deploy_metabase.sh
> +export PREFIX="app-pr-1625-"
I think this prefix will not make sense once this PR is merged.

2022-01-12 18:20 UTC, conbrad commented on openshift/metabase/oc_build_metabase.sh
> +export NAMESPACE="e1e498-dev"
I think these hardcoded namespaces should be parameterized so we can add metabase to our different environments.

2022-01-12 18:22 UTC, Sybrand approved these changes
If you have time, if you can throw in some TODO's re. not hard coding environments in the .sh files.

2022-01-17 17:47 UTC, conbrad approved these changes

2022-01-17 21:11 UTC, JulianForeman approved these changes

2022-06-06 18:46 UTC, closed without merging