HFI PDF Formatting changes
bcgov/wps pull request #1807
Opened 2022-03-24 17:38 UTC by conbrad

- Approved by @tessmgood offline if a printer is happy with it.

2022-03-25 15:56 UTC, Sybrand requested changes

2022-03-25 16:45 UTC, conbrad commented on api/app/hfi/pdf_generator.py
> +        'page-size': 'A4',
Changed to letter

2022-03-25 21:29 UTC, Sybrand approved these changes

2022-03-28 15:34 UTC, andrea-williams approved these changes

2022-03-28 15:41 UTC, andrea-williams commented on api/app/hfi/templates/daily_template.jinja.html
> +        <title>BC Wildfire Services - HFI Calculator - {{fire_centre_name}} - Date: {{date}}</title>
it's my pleasure to be of service(s)

2022-03-28 15:42 UTC, conbrad commented on api/app/hfi/templates/daily_template.jinja.html
> +        <title>BC Wildfire Services - HFI Calculator - {{fire_centre_name}} - Date: {{date}}</title>
Updated

2022-03-28 15:42 UTC, conbrad commented on api/app/hfi/templates/prep_template.jinja.html
> +      BC Wildfire Services - HFI Calculator - {{ fire_centre_name }} - Prep
Updated

2022-03-28 17:26 UTC, JulianForeman approved these changes

2022-03-28 21:23 UTC, merged