Grass Cure % Position Fix
bcgov/wps pull request #1852
Opened 2022-04-04 22:53 UTC by JulianForeman

2022-04-04 22:56 UTC, conbrad requested changes
Nice, just need to also add the change to the PDF generation

2022-04-04 23:11 UTC, JulianForeman commented
> Member

It looks like you already put grass cure next to fuel type in your template

2022-04-04 23:12 UTC, JulianForeman commented
> Nice, just need to also add the change to the PDF generation

I think you handled this in the pdf generation because we worked from an accurate mockup, not the app.

2022-04-04 23:15 UTC, conbrad commented
> > Nice, just need to also add the change to the PDF generation
> 
> I think you handled this in the pdf generation because we worked from an accurate mockup, not the app.

I think you're right, in that case LGTM

2022-04-04 23:16 UTC, conbrad requested changes

2022-04-04 23:16 UTC, conbrad commented on web/src/features/hfiCalculator/components/DailyViewTable.tsx
> +                  <TableCell>
This will need to be in it's own `StickCell` > `Table` tree

2022-04-05 22:34 UTC, tessmgood reviewed
Placement looking good - there is a weird styling gremlin now, lmk if it's quick to tidy:

There is a grey line under grass cure in daily tabs - but not in prep view. Seems like a cell outline or underline? it's visual noise I'd love to remove if possiblee
![Screen Shot 2022-04-05 at 3 31 42 PM](https://user-images.githubusercontent.com/16671373/161861853-3014209e-eadf-4bf5-9d95-188fe9e76829.png)

2022-04-05 22:37 UTC, tessmgood commented
Something has happened to our columns in daily tabs - is danger class label missing? Fire type onwards is offset 
![Screen Shot 2022-04-05 at 3 35 28 PM](https://user-images.githubusercontent.com/16671373/161862388-c4e61d08-17de-4674-aafa-65d2afb1ae01.png)

2022-04-05 22:45 UTC, andrea-williams commented
> Something has happened to our columns in daily tabs - is a label missing? HFI onwards is offset ![Screen Shot 2022-04-05 at 3 35 28 PM](https://user-images.githubusercontent.com/16671373/161862388-c4e61d08-17de-4674-aafa-65d2afb1ae01.png)

@tessmgood  you peeked too early! Still working on it, although I should have changes ready for you to review soon

2022-04-05 22:48 UTC, tessmgood commented
> > Something has happened to our columns in daily tabs - is a label missing? HFI onwards is offset ![Screen Shot 2022-04-05 at 3 35 28 PM](https://user-images.githubusercontent.com/16671373/161862388-c4e61d08-17de-4674-aafa-65d2afb1ae01.png)
> 
> @tessmgood you peeked too early! Still working on it, although I should have changes ready for you to review soon

oop - I think Julian tagged me for review yesterday, my b!

2022-04-06 15:39 UTC, conbrad approved these changes
Nice! Thanks for fixing that issue while you were working on the code!

2022-04-06 15:44 UTC, andrea-williams commented on web/src/features/hfiCalculator/components/StaticCells.tsx
> +    let isFirstDayOfPrep = false
Thanks :) Made it inline in prop param

2022-04-06 17:39 UTC, tessmgood approved these changes
Looks great and rule-breaking is 🦄 🌈

2022-04-06 17:40 UTC, Sybrand approved these changes

2022-04-06 18:06 UTC, merged