Story/default view temp graph/577
bcgov/wps pull request #606
Opened 2020-12-04 23:46 UTC by Kyubinhan

2020-12-07 23:12 UTC, andrea-williams approved these changes

2020-12-07 23:12 UTC, andrea-williams commented on web/src/features/fireWeather/components/graphs/TempRHGraph.tsx
> +  const gc = useMemoGraphCalculation(props, chartWidth)
I'd prefer to see `gc` renamed to `graphCalc` or something similar to make it more obvious what it is.

2020-12-08 00:37 UTC, Sybrand approved these changes

2020-12-08 00:44 UTC, Sybrand requested changes
Looking at the ticket, "active default toggles should be Actuals and HRDPS"  but I don't get HRDPS selected.

Unrelated to the ticket, but since you've re-factored it - why do we default to +40 degrees celcius?

2020-12-09 00:24 UTC, Sybrand approved these changes

2020-12-09 00:40 UTC, merged