Highlight min/max values in data tables
bcgov/wps pull request #854
Opened 2021-04-07 17:19 UTC by andrea-williams

2021-04-13 16:28 UTC, conbrad approved these changes
LGTM - just remove package-lock.json as mentioned offline

2021-04-13 16:53 UTC, Sybrand commented on web/src/features/fireWeather/components/tables/SortableTableByDatetime.tsx
> +      row.precipitation?.toFixed(PRECIP_VALUES_DECIMAL) ===
I think we need to exclude 0. If the max precip is 0, then we just have all the rows highlighted. I know it's mathematically correct, but it makes for a weird display i.m.h.o.

2021-04-13 17:00 UTC, Sybrand approved these changes
Can we have ambrose, and then one of the weather people give a look before we merge?
Also - I think the multiple highlights on precip. is weird when the max is 0.

2021-04-14 22:48 UTC, conbrad approved these changes

2021-04-15 00:13 UTC, conbrad approved these changes

2021-04-15 15:48 UTC, Sybrand approved these changes
Looks real pretty!

2021-04-15 15:53 UTC, conbrad requested changes

2021-04-15 15:53 UTC, conbrad commented on web/src/features/fireWeather/components/tables/SortableTableByDatetime.tsx
>  function SortableTableByDatetime<R extends WeatherValue>(props: Props<R>) {
A unit test suite for this component may be in order due to all the conditional branches and switches -- I'm not sure the cypress tests capture that and I think unit tests would be easier to write. WDYT?

2021-04-16 15:45 UTC, conbrad requested changes
Looks good, just a few more tests I think

2021-04-16 15:45 UTC, conbrad commented on web/src/utils/table.test.ts
> +  describe('getMinMaxValueCalculator', () => {
I think we should also add cases for when values are null and max value is 0

2021-04-16 15:45 UTC, conbrad commented on web/src/features/fireWeather/components/tables/SortableTableByDatetime.tsx
> +                          case 'precipitation':
Not sure if this is easier to write as a cypress test or unit test but I think we should add a test that checks that the `className` and `testId` are set for either `precipitation`, `delta_precipitation` or `total_precipitation`.

The easiest way would be to pull out a utility function that accepts the columns and does the switch logic so it's easier to test with jest, then just have the component import and use it.

More component-y way would be to use some like enzyme to shallow render the component and check it with the library assertions: https://devhints.io/enzyme

2021-04-16 20:44 UTC, conbrad approved these changes
🚀

2021-04-16 22:10 UTC, merged