Display observed values in Forecasts table
bcgov/wps pull request #985
Opened 2021-05-05 00:07 UTC by andrea-williams

2021-05-21 15:34 UTC, conbrad requested changes
Code looks good just might want to fix the spacing to be uniform with existing tables

<img width="799" alt="Screen Shot 2021-05-21 at 8 30 12 AM" src="https://user-images.githubusercontent.com/1447136/119162535-58155180-ba0f-11eb-84d5-bc698a185099.png">

2021-05-27 17:45 UTC, Sybrand approved these changes
Looks good - comment re. middleware but that's it (might be the Moderna speaking here...)

2021-05-27 17:45 UTC, Sybrand commented on web/src/app/store.ts
> +  middleware: () =>
You may want to exclude this when you push your source up.

2021-05-27 23:37 UTC, conbrad requested changes

2021-05-27 23:37 UTC, conbrad commented on web/src/features/fireWeather/components/tables/ComparisonTableRow.tsx
> +          switch (source) {
Lots of cyclomatic complexity with all these switch statements (I'd argue we should turn this on as a lint check: http://pylint.pycqa.org/en/latest/technical_reference/extensions.html#design-checker)

A simpler solution I'd propose is creating a map of `[WeatherVariable, formatFn]` and just lookup the function to call with the props and class. Lmk if you want more of an explanation.

2021-06-01 15:23 UTC, Sybrand approved these changes

2021-06-01 15:46 UTC, conbrad approved these changes

2021-06-01 16:37 UTC, merged